linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gocyclo:
    min-complexity: 19
  goconst:
    min-len: 3
    min-occurrences: 5
  lll:
    line-length: 160
  funlen:
    lines: 80
    statements: 45
  gomoddirectives:
    replace-local: true
  govet:
    enable-all: true
    settings:
      printf:
        funcs:
          - Tracef
          - Infof
          - Warnf
          - Errorf
          - Fatalf
          - Criticalf
          - Panicf
linters:
  enable-all: true
  fast: false
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godot
    - gofumpt
    - nonamedreturns
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wsl
    - err113
    # deprecated
    - execinquery
    - gomnd
issues:
  max-same-issues: 0
  exclude-use-default: true
  exclude:
    - "cyclomatic complexity .* of func `Test.*` is high"
    - "cyclomatic complexity .* of func `.*parseConfigItem` is high"
    - "Function name: parseConfigItem, Cyclomatic Complexity"
    - "cognitive complexity .* of func `Test.*"
    - "cognitive complexity .* of func `initConfiguration`"
    - "cyclomatic complexity .* of func `initConfiguration` is high"
    - 'Magic number: 0.01\D '
    - 'Magic number: 1\D '
    - 'Magic number: 2\D '
    - 'Magic number: 3\D '
    - 'Magic number: 10\D '
    - 'Magic number: 30\D '
    - 'Magic number: 16\D '
    - 'Magic number: 64\D '
    - 'Magic number: 100\D '
    - 'Magic number: 1024\D '
    - 'Magic number: 1e9\D '
    - 'Magic number: 0o644\D '
    - 'Magic number: 0o755\D '
    - 'Magic number: 0664\D '
    - 'Magic number: 100000\D '
    - 'Magic number: 65536\D '
    - 'Expect WriteFile permissions to be 0600 or less'
    - 'G204: Subprocess launched'
    - 'G114: Use of net/http serve function that has no support for setting timeouts'
    - 'RLIMIT_NOFILE contains underscore'
    - 'O_APPEND contains underscore'
    - 'O_WRONLY contains underscore'
    - 'O_CREATE contains underscore'
    - 'Duplicate words.*sadhajshdka'
    - 'FactorLog.*does not support error-wrapping directive'
    - "Function 'dump' has too many statements"
    - "Function 'parseConfigItem' has too many statements"
    - "Function 'startEmbeddedPerl' has too many statements"
    - "Function 'mainLoop' has too many statements"
    - "Function 'mainLoop' is too long"
    - "Function 'initConfiguration' has too many statements"
    - "Function 'printUsage' has too many statements"
    - "Function 'execCmd' has too many statements"
    - "Metric: modgearmanworker_workers_total Error: non-counter metrics"
    - 'local replacement are not allowed: pkg/'
    - "fieldalignment: struct"
    - "Function 'PrintUsageCheckGearman' has too many statements"
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test.*\.go
      linters:
        - errcheck
        - mnd
        - dupword
        - funlen
        - lll
