version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - godot
    - nonamedreturns
    - noinlineerr
    - paralleltest
    - perfsprint
    - tagliatelle
    - testpackage
    - wsl
    - wsl_v5
  settings:
    funlen:
      lines: 80
      statements: 45
    goconst:
      min-len: 3
      min-occurrences: 5
    gocritic:
      enabled-tags:
        - performance
        - style
        - experimental
    gocyclo:
      min-complexity: 19
    gomoddirectives:
      replace-local: true
    govet:
      enable-all: true
      settings:
        printf:
          funcs:
            - Tracef
            - Infof
            - Warnf
            - Errorf
            - Fatalf
            - Criticalf
            - Panicf
    lll:
      line-length: 160
  exclusions:
    warn-unused: true
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupword
          - errcheck
          - funlen
          - lll
          - mnd
          - gocyclo
        path: _test.*\.go
      - path: (.+)\.go$
        text: cyclomatic complexity .* of func `.*parseConfigItem` is high
      - path: (.+)\.go$
        text: 'Function name: parseConfigItem, Cyclomatic Complexity'
      - path: (.+)\.go$
        text: 'Magic number: 0.01\D '
      - path: (.+)\.go$
        text: 'Magic number: 2\D '
      - path: (.+)\.go$
        text: 'Magic number: 3\D '
      - path: (.+)\.go$
        text: 'Magic number: 5\D '
      - path: (.+)\.go$
        text: 'Magic number: 10\D '
      - path: (.+)\.go$
        text: 'Magic number: 30\D '
      - path: (.+)\.go$
        text: 'Magic number: 16\D '
      - path: (.+)\.go$
        text: 'Magic number: 100\D '
      - path: (.+)\.go$
        text: 'Magic number: 1024\D '
      - path: (.+)\.go$
        text: 'Magic number: 0o644\D '
      - path: (.+)\.go$
        text: 'Magic number: 0o755\D '
      - path: (.+)\.go$
        text: 'Magic number: 65536\D '
      - path: (.+)\.go$
        text: Expect WriteFile permissions to be 0600 or less
      - path: (.+)\.go$
        text: 'G204: Subprocess launched'
      - path: (.+)\.go$
        text: 'G114: Use of net/http serve function that has no support for setting timeouts'
      - path: (.+)\.go$
        text: FactorLog.*does not support error-wrapping directive
      - path: (.+)\.go$
        text: Function 'dump' has too many statements
      - path: (.+)\.go$
        text: Function 'parseConfigItem' has too many statements
      - path: (.+)\.go$
        text: Function 'startEmbeddedPerl' has too many statements
      - path: (.+)\.go$
        text: Function 'mainLoop' has too many statements
      - path: (.+)\.go$
        text: Function 'initConfiguration' has too many statements
      - path: (.+)\.go$
        text: Function 'execCmd' has too many statements
      - path: (.+)\.go$
        text: 'Metric: modgearmanworker_workers_total Error: non-counter metrics'
      - path: (.+)\.go$
        text: 'fieldalignment: struct'
      - path: (.+)\.go$
        text: Function 'printUsageCheckGearman' has too many statements
      - path: (.+)\.go$
        text: 'minmax: if statement can be modernized using min'
      - path: (.+)asciiTable\.go$
        text: 'var-naming: avoid meaningless package names'
      - path: (.+)\.go$
        text: 'net.* must not be called'
      - path: (.+)_test\.go$
        text: 'exec.Command.* must not be called'
      - path: (.+)statusworker\.go$
        text: 'with fmt.Appendf'
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
